config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :users

  root to: 'institutions#index'

  resources :institutions, except: :destroy do
    scope module: :institutions do
      resources :rooms, except: :destroy do
        resource :api, only: [:show]
      end
    end
  end

  get '/api/:id', to: 'api#show'
end

app/models/beacon.rb
# frozen_string_literal: true

class Beacon
  include Mongoid::Document
  store_in collection: 'appData'

  field :people_count, type: String
  field :time, type: String
  field :beacon_Id, type: String
end

app/models/institution.rb
# frozen_string_literal: true

class Institution
  include Mongoid::Document

  field :name, type: String

  has_many :rooms, dependent: :destroy, class_name: 'Institutions::Room'

  validates :name, presence: true

  include Mongoid::Timestamps
end

app/models/institutions/room.rb
# frozen_string_literal: true

module Institutions
  class Room
    include Mongoid::Document
    include Mongoid::Attributes::Dynamic

    store_in collection: 'rooms'

    field :name, type: String
    field :sensor_id, type: String
    field :institution_id, type: String
    field :beacon_id, type: String

    belongs_to :institution, class_name: 'Institution'

    validates :name, :sensor_id, :institution_id, presence: true

    include Mongoid::Timestamps

    def measurements
      Measurement.where(sensor_id: sensor_id)
    end
  end
end

app/models/measurement.rb
# frozen_string_literal: true

class Measurement
  include Mongoid::Document
  store_in collection: 'sensorDataAranet'

  field :humidity, type: String
  field :co2, type: String
  field :sensor_id, type: String

  validates :humidity, :co2, :sensor_id, presence: true

  def co2_limit
    return false unless co2.to_i > 1000

    true
  end

  def humidity_limit
    return false unless humidity.to_i > 50

    true
  end
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document

  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable

  ## Database authenticatable
  field :name, type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  validates :name, presence: true

  validates :name, uniqueness: true, case_sensitive: false

  def email_required?; false end

  def email_changed?; false end

  include Mongoid::Timestamps
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ApplicationController
  def show
    room = Institutions::Room.find_by(beacon_id: params[:id])

    render json: json_data(room)
  end

  private

  def json_data(room)
    {
      room_data: room,
      measurements: room.measurements.last,
      co2_limit: room.measurements.last.co2_limit,
      humidity_limit: room.measurements.last.co2_limit,
      beacon_data: Beacon.where(beacon_Id: params[:id]).last
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password, :password_confirmation])
  end
end

app/controllers/institutions/apis_controller.rb
# frozen_string_literal: true

module Institutions
  class ApisController < ApplicationController
    def show
      room = Institutions::Room.find(params[:room_id])
      json = { room_data: room, measurements: room.measurements.last }

      render json: json
    end
  end
end

app/controllers/institutions/rooms_controller.rb
# frozen_string_literal: true

module Institutions
  class RoomsController < ApplicationController
    before_action :authenticate_user!

    def show
      room = Institutions::Room.find(id: params[:id])

      @presenter = Rooms::ShowPresenter.new(room)
    end

    def new
      institution = Institution.find(params[:institution_id])
      room = Institutions::Room.new(institution: institution)

      @presenter = FormPresenter.new(form: room)
    end

    def create
      institution = Institution.find(params[:institution_id])
      room = Institutions::Room.new(institution: institution)

      if room.update(create_params)
        redirect_to institution_room_path(institution_id: institution.id, id: room.id)
      else
        redirect_to 'new'
      end
    end

    private

    def create_params
      params.require(:institutions_room).permit(:name, :sensor_id)
    end
  end
end

app/controllers/institutions_controller.rb
# frozen_string_literal: true

class InstitutionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @presenter = Institutions::IndexPresenter.new(Institution.all)
  end

  def show
    institution = Institution.find(params[:id])

    @presenter = Institutions::ShowPresenter.new(institution)
  end

  def new
    institution = Institution.new

    @presenter = FormPresenter.new(form: institution)
  end

  def create
    institution = Institution.new

    if institution.update(create_params)
      redirect_to institutions_path
    else
      redirect_to 'new'
    end
  end

  private

  def create_params
    params.require(:institution).permit(:name)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/institutions/_form.html.slim
= simple_form_for form, url: institutions_path do |f|
  .card
    .card-header
      .card-title
        = 'Pievienot jaunu institūciju'
    .card-body
      = f.input :name
    .card-footer
      = f.button :submit, class: 'btn btn-primary'
      = link_to('Atcelt', cancel_path, class: 'btn btn-secondary')

app/views/institutions/index.html.slim
h1.my-4
  | VPP 6.6

  = link_to new_institution_path, class: 'btn btn-primary float-right' do
    |Pievienot

  .row
    - if @presenter.institutions.present?
      - @presenter.institutions.each do |institution|
        .col-lg-4.col-sm-6.mb-4
          .card.h-100
            a href="#{institution_path(institution)}"
              img.card-img-top alt="" src="https://www.nicepng.com/png/detail/154-1549461_3d-house-vector-vector-houses-icon-png.png"
            .card-body
              h3.card-title
                a
                  = institution.name
    - else
      .alert.alert-danger role="alert"
        | Nav pievienota neviena iestāde!

app/views/institutions/new.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item
      a href="#{@presenter.institutions_link}"  Iestādes
    li.breadcrumb-item.active aria-current="page"
      | Pievienot jaunu

= render 'form', form: @presenter.form, cancel_path: institutions_path

app/views/institutions/rooms/_form.html.slim
= simple_form_for form, url: institution_rooms_path do |f|
  .card
    .card-header
      .card-title
        = 'Pievienot jaunu telpu'
    .card-body
      = f.input :name
      = f.input :sensor_id
      = f.input :beacon_id
    .card-footer
      = f.button :submit, class: 'btn btn-primary'
      = link_to('Atcelt', cancel_path, class: 'btn btn-secondary')

app/views/institutions/rooms/new.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item
      a href="#{@presenter.institutions_link}"  Iestādes
    li.breadcrumb-item
      a href="#{@presenter.institution_link(@presenter.form.institution)}"
        = @presenter.form.institution.name
    li.breadcrumb-item.active aria-current="page"
      | Pievienot jaunu

= render 'form', form: @presenter.form, cancel_path: institution_path(@presenter.form.institution)

app/views/institutions/rooms/show.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item
      a href="#{@presenter.institutions_link}"  Iestādes
    li.breadcrumb-item
      a href="#{@presenter.institution_link(@presenter.room.institution)}"
        = @presenter.room.institution.name
    li.breadcrumb-item.active aria-current="page"
      = "Telpa: #{@presenter.room.name}"

- if @presenter.room_measurement.present?
  .jumbotron.jumbotron-fluid class=(@presenter.quality_in_limits ? 'bg-green' : 'bg-red')
    .container
      - if @presenter.quality_in_limits
        h1.display-4 = "Telpa: #{@presenter.room.name}"
        | Telpas gaisa kvalitāte ir normas robežās!
      - else
        h1.display-4 = "Telpa: #{@presenter.room.name}"
        | Uzsāciet telpas vēdināšanu!

  .row
    .col-sm-6
      .card
        .d-flex.justify-content-center
          img.card-img-top.measurement-img src="https://www.flaticon.com/svg/static/icons/svg/3209/3209891.svg"
        .card-body class=(@presenter.co2_check ? 'bg-success' : 'bg-danger')
          h1.card-title.text-light
            | Co2 (ppm)
          h1.card-title.text-light
            = @presenter.room_measurement.co2
    .col-sm-6
      .card
        .d-flex.justify-content-center
          img.card-img-top.measurement-img src="https://www.flaticon.com/svg/static/icons/svg/2784/2784423.svg"
        .card-body class=(@presenter.humidity_check ? 'bg-success' : 'bg-danger')
          h1.card-title.text-light
            | Mitrums (%)
          h1.card-title.text-light
            = "#{@presenter.room_measurement.humidity} %"

    #room-measurements

- else
  .jumbotron.jumbotron-fluid
    .container
      h1.display-4 = "Telpa: #{@presenter.room.name}"

  .alert.alert-danger role="alert"
    | Telpas gaisa kvalitātei nav neviena mērījuma!

app/views/institutions/show.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item
      a href="#{@presenter.institutions_link}"  Iestādes
    li.breadcrumb-item.active aria-current="page"
      = @presenter.institution.name

h1.my-4
  = @presenter.institution.name

  = link_to new_institution_room_path(institution_id: @presenter.institution.id), class: 'btn btn-primary float-right' do
    |Pievienot

  - if @presenter.institution.rooms.present?
    .row
      - @presenter.institution.rooms.each do |room|
        .col-lg-4.col-sm-6.mb-4
          .card.h-100
            a href=institution_room_path(institution_id: @presenter.institution.id, id: room.id)
              img.card-img-top alt="" src="https://www.pngitem.com/pimgs/m/379-3799346_3d-room-design-template-hd-png-download.png" /
            .card-body
              h3.card-title
                a
                  = "Telpa: #{room.name}"
  - else
    .alert.alert-danger role="alert"
      | Iestādei nav pievienota neviena telpa!

app/views/layouts/application.html.slim
doctype html
html lang="lv"
  head

    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body
    .container
      div
        - if current_user.present?
            = current_user.name
        .float-right
          - if user_signed_in?
            = link_to 'Iziet', destroy_user_session_path
          - elsif request.env['PATH_INFO'] == '/users/sign_up'
            return
          - elsif request.env['PATH_INFO'] != '/users/sign_in'
            = link_to 'Pieslēgties', new_user_session_path
      = yield

app/views/rooms/show.html.slim
nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item
      a href="#{@presenter.institutions_link}"  Iestādes
    li.breadcrumb-item
      a href="#{@presenter.institution_link(@presenter.room.institution)}"
        = @presenter.room.institution.name
    li.breadcrumb-item.active aria-current="page"
      = "Telpa Nr. #{@presenter.room.name}"

.jumbotron.jumbotron-fluid
  .container
    h1.display-4 = "Telpa Nr. #{@presenter.room.name}"

- if @presenter.room_measurement.present?

  - if @presenter.quality_in_limits
    .alert.alert-success role="alert"
      | Telpas gaisa kvalitāte ir normas robežās!
  - else
    .alert.alert-danger role="alert"
      | Uzsāciet telpas vēdināšanu!

  .row
    .col-sm-6
      .card
        .d-flex.justify-content-center
          img.card-img-top.measurement-img src="https://www.flaticon.com/svg/static/icons/svg/2784/2784423.svg"
        .card-body class=(@presenter.co2_check ? 'bg-success' : 'bg-danger')
          h5.card-title
            | Co2 (ppm)
          h1.card-title
            = @presenter.room_measurement.co2
    .col-sm-6
      .card
        .d-flex.justify-content-center
          img.card-img-top.measurement-img src="https://www.flaticon.com/svg/static/icons/svg/3209/3209891.svg"
        .card-body class=(@presenter.humidity_check ? 'bg-success' : 'bg-danger')
          h5.card-title
            | Mitrums (%)
          h1.card-title
            = "#{@presenter.room_measurement.humidity} %"

- else
  .alert.alert-danger role="alert"
    | Telpas gaisa kvalitātei nav neviena mērījuma!